name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build backend Docker image
      run: docker build ./backend --file ./backend/Dockerfile --tag aichat-backend:${{ github.sha }}
    - name: Build frontend Docker image
      run: docker build ./frontend --file ./frontend/Dockerfile --tag aichat-frontend:${{ github.sha }}
